export let tabEtudiants = [
  {
    id: 1,
    nom: "Dupont",
    prenom: "Jean",
    age: 22,
    courriel: "jean.dupont@exemple.com",
    programme: "Informatique",
    moyenne: 85,
  },
  {
    id: 2,
    nom: "Martin",
    prenom: "Marie",
    age: 20,
    courriel: "marie.martin@exemple.com",
    programme: "Biologie",
    moyenne: 92,
  },
  {
    id: 3,
    nom: "Chen",
    prenom: "Li",
    age: 21,
    courriel: "li.chen@exemple.com",
    programme: "Physique",
    moyenne: 88,
  },
  {
    id: 4,
    nom: "Patel",
    prenom: "Ankit",
    age: 23,
    courriel: "ankit.patel@exemple.com",
    programme: "Chimie",
    moyenne: 81,
  },
  {
    id: 5,
    nom: "Bernard",
    prenom: "Claire",
    age: 23,
    courriel: "claire.bernard@example.com",
    programme: "Physique",
    moyenne: 78,
  },
  {
    id: 6,
    nom: "Ahmed",
    prenom: "Sara",
    age: 20,
    courriel: "sara.ahmed@exemple.com",
    programme: "Médecine",
    moyenne: 94,
  },
  {
    id: 7,
    nom: "Demir",
    prenom: "Emre",
    age: 19,
    courriel: "emre.demir@exemple.com",
    programme: "Histoire",
    moyenne: 87,
  },
  {
    id: 8,
    nom: "Silva",
    prenom: "Beatriz",
    age: 21,
    courriel: "beatriz.silva@exemple.com",
    programme: "Philosophie",
    moyenne: 84,
  },
  {
    id: 9,
    nom: "Robert",
    prenom: "Nicolas",
    age: 19,
    courriel: "nicolas.robert@example.com",
    programme: "Informatique",
    moyenne: 88,
  },
  {
    id: 10,
    nom: "Okafor",
    prenom: "Chinedu",
    age: 23,
    courriel: "chinedu.okafor@exemple.com",
    programme: "Droit",
    moyenne: 82,
  },
  {
    id: 11,
    nom: "Moreau",
    prenom: "Julie",
    age: 21,
    courriel: "julie.moreau@example.com",
    programme: "Économie",
    moyenne: 95,
  },
  {
    id: 12,
    nom: "Smith",
    prenom: "Emma",
    age: 21,
    courriel: "emma.smith@exemple.com",
    programme: "Arts",
    moyenne: 89,
  },
  {
    id: 13,
    nom: "Singh",
    prenom: "Raj",
    age: 22,
    courriel: "raj.singh@exemple.com",
    programme: "Informatique",
    moyenne: 93,
  },
  {
    id: 14,
    nom: "Ivanova",
    prenom: "Elena",
    age: 21,
    courriel: "elena.ivanova@exemple.com",
    programme: "Psychologie",
    moyenne: 85,
  },
  {
    id: 15,
    nom: "Yoshida",
    prenom: "Kenji",
    age: 20,
    courriel: "kenji.yoshida@exemple.com",
    programme: "Biologie",
    moyenne: 91,
  },
  {
    id: 16,
    nom: "Laurent",
    prenom: "Alice",
    age: 21,
    courriel: "alice.laurent@example.com",
    programme: "Psychologie",
    moyenne: 77,
  },
  {
    id: 17,
    nom: "Nguyen",
    prenom: "Thu",
    age: 21,
    courriel: "thu.nguyen@exemple.com",
    programme: "Mathématiques",
    moyenne: 87,
  },
  {
    id: 18,
    nom: "Fernandez",
    prenom: "Carlos",
    age: 22,
    courriel: "carlos.fernandez@exemple.com",
    programme: "Physique",
    moyenne: 74,
  },
  {
    id: 19,
    nom: "Mbappe",
    prenom: "Kofi",
    age: 19,
    courriel: "kofi.mbappe@exemple.com",
    programme: "Histoire",
    moyenne: 82,
  },
  {
    id: 20,
    nom: "Goldstein",
    prenom: "Rachel",
    age: 21,
    courriel: "rachel.goldstein@exemple.com",
    programme: "Philosophie",
    moyenne: 88,
  },
];
